<?php

namespace Database\Seeders;

use App\Models\Ensemble;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EnsembleSeeder extends Seeder
{
    private $seeds;

    public function __construct()
    {
        $this->seeds = $this->buildSeeds();
    }
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach($this->seeds AS $seed){
            Ensemble::create(
                [
                    'id' => $seed[0],
                    'ensemble_name' => $seed[1],
                    'abbr' => $seed[2],
                    'category_id' => $seed[3],
                    'directed_by' => $seed[4],
                    'descr' => $seed[5],
                    'logo_file' => (array_key_exists(6, $seed) ? $seed[6] : ''),
                ]
            );
        }
    }

    private function buildSeeds()
    {
        return [
            [1,'Nonesuch','N',10,'Rick  Retzko','Classic Sounds Honors, under the direction of Mr. Patrick Hachey, is the premier curricular ensemble as the most select Concert Choir at Roxbury High School. Its 49 members were selected by a placement audition during the spring of last year. Students are chosen based upon their musical audition (tone quality, intonation, musicianship, ability to hold parts independently, preparation, tonal memory) and their attitude (ability to work with others, reliability, enthusiasm, dependability).
As the most challenging choir in the curricular program, Classic Sounds is a five-credit curricular, honors course at Roxbury. Classic Sounds Honors, as one Roxburyâ€™s traveling choirs, will be preparing its own concert repertoire to perform at festivals, competitions, and local performances throughout the year in addition to doing the major choir activities (Winter Concert, Roxbury Invitational, Spring Masterworks Concert). Classic Sounds Honors will be performing challenging music of a high level from the traditional choral repertoire including classics, madrigals, spirituals, and a cappella contemporary choir works. A member of Classic Sounds Honors is responsible for being at all Classic Sounds Honors performance dates.
In 2017, the group was named first place Mixed Choir AA with a Superior rating, and Best OVerall CHoir at the Dorney Park Music in the Parks Festival. In 2016, Classic Sounds was chosen as one of three high school mixed choirs to perform at the American Choral Directors Eastern Division Convention, the fourth time since 2004 they were selected for this honor. At the 2016 Williamsburg/VA Beach Music Festival, the group earned first place Mixed Choir AAA and a Superior rating, Bases section award, Best OVerall CHoir, and the Sweepstakes Award for the highest scoring choir at all Williamsburg/VA Beach festivals all season. In 2015, Classic Sounds was named first place Mixed Choir with a Superior rating at the Dorney Park Music in the Parts Festival. At the Boston Heritage Festival in 2014, Classic Sounds Honors earned first place Mixed Choir, a Gold rating, and, together with Roxbury Revelation, won the Sweepstakes Award for top choral program. At the 2010 North American Virginia Beach Music Festival, Classic Sounds was named first place Concert Choir with a Superior rating, Best Overall COncert CHoir, and, together with Roxbury Vocal Jazz, earned the Sweepstakes award for the highest average score from one school at the festival. In 2006, the group was one of three high school choirs from the East Coast chosen to perform at the American Spiritual Festival at Penn State. Classic Sounds Honors has twice been selected to perform at Carnegie Hall.
Classic Sound Honors has received Superior rations at every festival it has attended for the past 28 years.','1513618912.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
            [2,'Cinnamins','C',12,'Fredric  Retzko','Test Five','1513625259.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[3,'Seneca Singers','SS',10,'Robert DiLauro','Seneca Singers is one of two audition choirs at Seneca High School in Tabernacle, NJ.  The group is comprised of 27 of the highest level singers in the school.  They are always in high demand in the community and perform at various competitions and festivals throughout the year.  Seneca is thrilled to be back at Roxbury this year!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[5,'Chamber Singers','CS',10,'Dustin Ramirez','Chamber Singers is a select group made up of 20 singers in grades 10-12 from The Stony Brook School in Stony Brook, NY.  This group participates in many contests throughout New York, the Tri-State area, and the United States, consistently receiving superior ratings and first place awards.  Last year, Chamber Singers received the caption for &quot;Best Repertoire&quot; and second place at the NYC Fame Concert Choir Contest.  Other performances include the 2013 Presidential Inauguration festivities and the 2016 World Movement Day Conference in New York City.  This year, the Chamber Singers will compete at FAME NYC, Roxbury H.S., and Music in the Parks.  They are under the direction of Dustin Ramirez.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[6,'East Brunswick Concert Choir','EBCC',10,'Jami De Siena & Zachary Gates','The East Brunswick High School Concert Choir is a 49-voice auditioned mixed choir comprised of students in grades 10-12.The choir performs regularly throughout the school year at school events and throughout the community. The entire choral program at East Brunswick High School involves almost 300 students in five choirs.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[7,'Vox Central Jazz','VCJ',11,'Randy White','Vox Central Jazz performs often and has quickly earned the reputation of being an entertaining and musically advanced ensemble, promoting the American style of Jazz. Vox has earned consistently high honors at the Berklee College of Music High School Jazz Festival, the Roxbury Invitational, and the NJAJE State Vocal Jazz Festival. Vox students have won individual soloist awards and section awards at these events to go along with the strong group performances.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[8,'Hopewell Valley Chamber Singers','HVCS',10,'Randy White','The Hopewell Valley Chamber Singers are the premiere choral ensemble at Hopewell Valley  Central High School.  The choir travels frequently, completing tours to Italy, Germany, Austria, Czech Republic, Switzerland and Slovakia where they performed in the historic locations of St. Peter\'s Basilica, St. Marks Cathedral, the Pantheon, Prague and more. The Chamber Singers have also made recent appearances in Maryland, Virginia, Florida, Illinois, and New York.  The Chamber Singers consistently receive top rankings and exemplary sight reading ratings at events such as the Roxbury Invitational and the NJ-ACDA Choral Festival.  It\'s members receive Honors Level credit and represent the highest level of musicians at Central High School.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[9,'Warren Hills Select Choir','WHSC',10,'Lauren M. Voight','Warren Hills Select Choir is an auditioned extra-curricular group that meets on Tuesday evenings.  This group enjoys singing all kinds of challenging music for mixed choir.  Many thanks to Roxbury for hosting this festival and having us back to participate.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[10,'Warren Hills Rock & Pop Chorus','WHRPC',12,'Lauren M. Voight','Warren Hills Rock and Pop is an extra-curricular group made up of auditioned members from our Select Choir.  We are so grateful to the Roxbury Choral Program for welcoming us back!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[11,'John P. Stevens High School A Cappella Ensemble','JPSHSACE',10,'Matthew C. Lee','The John P. Stevens High School A cappella Ensemble is an auditioned choir that rehearses once a week. A cappella Ensemble has consistently received gold, superior, and first place ratings at local, national, and international choral festivals, including the World Strides Heritage Festival, the New Jersey ACDA High School Choir Festival, and Festivals of Music. Last year, A cappella received first place and a Gold rating from the Worldstrides Heritage Music Festival in Chicago, Illinois, where they also received the Adjudicatorâ€™s Award and the Choral Sweepstakes Award.  A cappella Ensemble competed in the Sing N Joy Princeton 2019 International Choral Festival and won the Youth Choirs category with a gold diploma. In 2017 A cappella also achieved the title of Category Winner in Sacred Music at the Sing N Joy Princeton 2017 Festival with a gold diploma. In 2019, A cappella shared the stage with 4 other high school choirs in a performance of Carmina Burana with the New Jersey Youth Symphony at NJPAC. The JPS A cappella Ensemble also performed at the 2017 National Association for Music Education Eastern Division Conference in Atlantic City. In April of this year, they will making their Carnegie Hall Debut. Many members of the J.P. Stevens Choir program are selected each year to participate in Central Jersey Region Choir, New Jersey All-State Choir, All-Eastern Choir, and All-National Honor Choirs. They are excited to return to the Roxbury Stage.','1515530757.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[12,'Midlothian City Lights','MCL',13,'Michelle Graham','City Lights is the women&#39;s show choir from Midlothian High School in Midlothian, VA.  City Lights was the first women&#39;s show choir in Chesterfield County founded in fall of 1985.  The 2016 Competition Show highlights the color RED.  The color RED can be used to describe love, emotion, passion and a face flushed with a fever.  We hope that you enjoy our passionate and exciting reaction to this single color.  City Lights is under the direction of Michelle Graham with choreography by Ashley Carr.  Our dance captains are Casey Berry, Elizabeth Ferguson and Andrea Taylor.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[13,'Midlothian Just For Show','MJFS',13,'Michelle Graham','Just For Show is the mixed show choir from Midlothian High School in Midlothian, VA.  HIGHER is the theme of our 2016 Competition Show.  Come with us on a ride that will propel you higher than you have ever been before! Go up on the roof, journey on a flight that leads to heaven and then follow us back home.  Just For Show is  under the direction of Michelle Graham with choreography by Terrell Dean.  Our dance captains are Bailey Blair, John El-Jor, Rachel Kendrick, Anna Luther, Johnny Rogers and Eileen Steinmacher.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[15,'Hershey Boyz Noyz','HBN',12,'Joseph Farrell, Danielle Buckingham, student teacher, Cather','Hershey Boyz Noyz is a non-auditioned Men\'s Choir that meets daily.  It is one of three curricular choirs at Hershey High School.  Repertoire studied ranges from the Renaissance to popular.  Boyz Noyz wishes to thank Roxbury High School for inviting us to this great Invitational!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[16,'Hershey Cantabile','HC',10,'Joseph Farrell','Hershey High School Cantabile is an auditioned ensemble that meets daily.  It is one of three choirs in the school\'s vocal music program.  Repertoire performed by Hershey Cantabile ranges from Renaissance to popular.
Since 1999, HHS Cantabile has annually received Superior and Excellent ratings in numerous festivals including the 2001, 2010, 2012, 2015, 2016, 2017, 2018 and 2019 Roxbury Invitationals, where the group was selected to the Evening Showcase performance in the Concert Choir division.  In 2013, 2016 and 2017, Cantabile earned Grand Champion recognition at the Roxbury High School Invitational.  Additionally, HHS Cantabile has performed at the 2004 and 2015 Pennsylvania Music Educators Association State Conventions.
Hershey Cantabile has performed on the campuses of Bucknell University, Lebanon Valley College, Moravian College, the Pennsylvania State University, the University of Pittsburgh and Susquehanna University.
In 2006, 2008, 2011 and 2014 members of Cantabile embarked on performance tours of Italy, Slovenia, Austria, Hungary and the Czech Republic.
HHS choirs frequently share the stage with the Central Pennsylvania Symphony, Harrisburg Symphony, Youth Symphony and Hershey Symphony. HHS Choirs wish to thank Roxbury High School and their music faculty for the invitation to this wonderful festival.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[17,'Hershey In Voce','HIV',10,'Joseph Farrell, Danielle Buckingham, student teacher, Cather','Hershey High 1School In Voce is a non-auditioned womens\' ensemble that meets during the school day.  It is one of three choirs at Hershey High School.  Repertoire ranges from Renaissance to popular.  In Voce has performed at the Capital Rotunda, with the Central Pennsylvania Symphony, Harrisburg Symphony, Harrisburg Youth Symphony, Hershey Symphony and have been past participants at the Roxbury Choir Invitational, earning gold and silver ratings. Hershey High School wishes to thank Roxbury High School and their Music Department for their gracious hospitality and coordination of this fine event.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[18,'West Milford Highland Jazz','WMHJ',11,'Doug Heyburn','The Highland Jazz vocal ensemble from West Milford High School is happy to be back participating in the Roxbury Choral Invitational.   They are under the direction of Doug Heyburn and accompanied by pianist Mitch Schechter.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[19,'Glenwood Titan Fever','GTF',13,'Jeff Gemar','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[20,'Roxbury Treble Choir','RWE',10,'R. Daniel Salyerds','The Roxbury Treble Choir, under the direction of Mr. R. Daniel Salyerds, is the department\'s only treble voice curricular group.  This choir is designed to acquaint the incoming freshmen with the Roxbury Choir Program, and provide them with the opportunity to develop good vocal technique and music reading skills.','1513697844.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[21,'Roxbury Concert Choir','RCC',10,'Patrick Hachey &amp; Krista Sweer','The Roxbury Concert Choir, an 70-member balanced chorus of mixed voices, is one of Roxbury\'s curricular groups.  This choir meets as a five credit class in its own choir periods and sings a variety of traditional choral literature.  The Concert Choir has been designed to suit the needs of two types of students: those who enjoy vocal music but do not have the time to pursue a select group such as Classic Sounds or Roxbury Chorale, and those who wish to improve their skills in order to make a select group in the future.  The students perform in the Winter and Spring Masterworks concerts as well as the Roxbury Festival.','1513697766.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[22,'Roxbury Chorale','RC',10,'Krista Sweer','The Roxbury Chorale is a select group of upperclassmen who meet every other day in one of two class sections.  This curricular ensemble is entering its 22nd season.  Last   spring,  the   Roxbury   Chorale   earned   first   place   Concert   Choir   Open with   a   Superior   rating   at   the   Hershey   Park   Music   in   the   Parks   Festival.  In 2018,   the   group   received   third   place   Mixed   Choir   AA   with   a   Gold   rating   at   the WorldStrides   OnStage   Music   Festival   in   Washington,  D.C.  In   previous   years, Roxbury   Chorale   was   named   first   place   in   its   division   at   the   Williamsburg/ VA Beach  Music  Festival, the  Boston  Heritage  Music  Festival, Fiesta-val  in Williamsburg,  VA,  Music   in   the   Parks   Festival   at   Great   Adventure   and   Dorney Park,  Music   in   the   Parks   in   Richmond,  VA,  and   the   New   England   Music   Festival.','1513697861.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[23,'Roxbury Broadway Theatre Show Choir','RBT',10,'R. Daniel Salyerds/Rebecca Pietras','The Broadway Theater Show Choir is an outgrowth of the choral program here at Roxbury.  With the vocal instruction of Dan Salyerds and dance expertise of Rebecca Pietras, the Broadway Theater Show Choir has grown into a class of about 40 students.  It offers students the opportunity to work on their singing and dancing in one class.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[24,'Roxbury Vocal Jazz','RVJ',11,'Krista Sweer','Roxbury Vocal Jazz, under the direction of Mrs. Krista Sweer, is the second select jazz choir at Roxbury.  Now in its 21st season, the group performs at various festivals and competitions, as well as at the Roxbury Jazz Night.  Last year,  Vocal Jazz received  second   place   Jazz   Choir   with   a   Superior   rating   at the   Hershey   Park   Music   in   the   Parks   Festival.  In   2018,   the   group   received   second   place   Jazz   Choir   AA   with   a   Gold   rating   at   the   WorldStrides   OnStage Music   Festival   in   Washington,  D.C.  In   2017,   the   group   was   awarded   second place   Jazz   Choir   with   a   Superior   rating   at   the   Dorney   Park   Music   in   the   Parks Festival.  In   2013,   the   group   was   honored   to   perform   with   the   Grammy   Award winning   New   York   Voices.  Vocal   Jazz   has   previously   received   high   awards   at the   Boston   Heritage   Music   Festival,  Fiesta-val   in   Williamsburg,  VA,  the   Virginia Beach   Music   Festival,  Music   in   the   Parks   at   Great   Adventure   and   Dorney   Park, and   Music   in   the   Parks   in   Richmond,  VA.','1513697786.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[25,'Cab Calloway JazzChords of Calloway','CCJCC',11,'Martin Lassman','The JazzChords of Calloway is the jazz choir from the Cab Calloway School for the Arts, a middle and high school Arts Magnet School, in Wilmington Delaware.  The students meet as a class every other day for 80 minute blocks.  This is our fourth time performing at the Roxbury Invitational and we always enjoy listening to all the choirs.  Good luck to everyone!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[26,'Cab Calloway Women\'s Jazz Choir','CCWJC',11,'Martin Lassman','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[27,'Roxbury Revelation','RR',11,'Patrick Hachey','Roxbury Revelation is the Roxbury Vocal Music Department\'s premier extracurricular ensemble.  The group, which performs under the direction of Mr. Patrick Hachey, is one of the only choirs of its kind in the state, and has received many state and notional honors in the past 25 years.  Last  spring, Roxbury  Revelation  earned  first  place  Jazz  Choir  with  a Superior   rating   at   the   Hershey   Park   Music   in   the   Parks   Festival.  In   2018, the   group   was   named   first   place   Jazz   Choir   AA   with   a   Gold   rating   and, together   with   Classic   Sounds   Honors,  won   the   Sweepstakes   Award   for   top choral   program   at   the   WorldStrides   OnStage   Music   Festival   in   Washington, D.C.  In   2017,   the   group   was   awarded   first   place   Jazz   Choir   with   a   Superior rating   at   the   Dorney   Park   Music   in   the   Parks   Festival.  In   2016,   the   group received   first   place   Vocal   Jazz   with   a   Superior   rating   at   the   Williamsburg/ VA Beach   Music   Festival.   In   2015,   Roxbury   Revelation   earned   first   place   Jazz Choir,  a   Superior   rating,  and   Best   Overall   Choir   at   the   Dorney   Park   Music   in the   Parks   Festival.  In   2014,   the   group   won   first   place   Jazz   Choir   and   a   Gold rating   at   the   Boston   Heritage   Music   Festival.  The   group   was   honored   to   be named   Outstanding   Choral   Group   of   the   Festival,  receive   the   Adjudicator Award, and, together  with  Classic  Sounds  Honors, win  the  Sweepstakes Award  for  top  choral  program.  In  2013,  the  group  performed  with  the Grammy   Award   winning   New   York   Voices.','1513697804.jpg','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[28,'Roxbury Classic Sounds Honors','RCSH',10,'Patrick Hachey','Classic Sounds Honors is the most select concert choir at Roxbury High School.  Its 40 members were selected by audition during the spring of last year.  Classic Sounds Honors meets every other day in one class session, and performs challenging concert repertoire to perform at festivals and competitions.  Its members earn honors credit for their participation.
Last   spring,  the   group   was   selected   to   perform   at   the   National   Association for   Music   Educators   Eastern   Division   Convention   in   Pittsburgh,  PA.   Later that  season  Classic  Sounds  earned  first  place  Concert  Choir  AA  with  a Superior   rating,  and   Best   Overall   Choir   at   the   Hershey   Park   Music   in   the Parks   Festival.  In   2018,   the   group   was   named   first   place   Mixed   Choir   AA with  a  Gold  rating, Best  Overall  Choir, and, together  with  Roxbury Revelation, won  the  Sweepstakes  Award  for  top  choral  program  at  the WorldStrides  OnStage  Music  Festival  in  Washington, D.C.  In  2017,  the group   was   named   first   place   Mixed   Choir   AA   with   a   Superior   rating,  and Best   Overall   Choir   at   the   Dorney   Park   Music   in   the   Parks   Festival.  In   2016, Classic   Sounds   was   chosen   as   one   of   three   high   school   mixed   choirs   to   per-form  at  the  American  Choral  Directors  Eastern  Division  Convention, the fourth  time  since  2004  they  were  selected  for  this  honor.  At  the  2016 Williamsburg/ VA   Beach   Music   Festival,  the   group   earned   first   place   Mixed Choir   AAA   and   a   Superior   rating,  Bass   section   award,  Best   Overall   Choir, and  the  Sweepstakes  Award  for  the  highest  scoring  choir  at  all Willamsburg/ VA   Beach   festivals   all   season.  In   2015,   Classic   Sounds   was named   first   place   Mixed   Choir   I   with   a   Superior   rating   at   the   Dorney   Park Music   in   the   Parks   Festival.  Classic   Sounds   Honors   has   twice   been   selected to   perform   at   Carnegie   Hall. Classic   Sounds   Honors   has   received   Superior   ratings   at   every   festival   it has   attended   for   the   past   30   years.','1513697822.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[29,'Sterling Silvertones','SS',13,'Alex Younger','The Sterling Silvertones is a select show choir ensemble featuring some of the brightest performers at Sterling High School. These students represent the top echelon of the vocal performing arts program at our school. The group is directed by Mr. Alex Younger and Mrs. Brooke Galezniak.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[30,'Symphonic Choir (honors)','SC',10,'John Wilson','The Symphonic Choir is the premier curricular choral ensemble at Bridgewater-Raritan High School. Its 42 members were selected by audition during the spring of last year. The Symphonic Choir meets every day, where they rehearse challenging repertoire for performances and festivals. Its members earn honors credit for their participation. Students are selected for this group based on their musical audition (tone quality, intonation, musicianship, sight-reading, independence, preparation, tonal memory) and their attitude (ability to work with others, reliability, enthusiasm, dependability). We are proud to say that the Symphonic Choir has earned gold or superior ratings at each festival they have participated in for the last ten years.
This year, the Symphonic Choir was fortunate enough to participate in a workshop with Dr. Jerry Blackstone, Director of Choral Activities at the University of Michigan, at an event hosted by Trish Joyce and the New Jersey Youth Chorus. They were also invited to sing the National Anthem  on live television at a Rutgers University basketball game.
Recent performance highlights include the NYC premiere of Eric Banks&#39; &#34;I Am Among Them&#34;  with the Schola Cantorum on Hudson conducted by Deborah Simpkin King (February 2016), and an April 2016 performance at Carnegie Hall with CODA Concerts featuring works by MoÄnik, Handel, and Stacey V. Gibbs. Coming up, the Symphonic Choir will collaborate with the New Jersey Chamber Singers and their director, Reid Masters, in a concert called &#34;Psalms from Age to Age&#34; on April 1st and 2nd in Pluckemin and Toms River respectively.
Mr. Wilson and the Symphonic Choir wish to thank Ms. Lori Lynch, Mr. Patrick Hachey, the adjudicators, and all the student and parent volunteers for all they do to make this event such a high quality and meaningful experience!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[31,'JazzChords of Calloway','JCC',11,'Director Name','The JazzChords of Calloway is a choir class at the Cab Calloway School of the Arts in Wilmington, Delaware. The choir has 36 students but generally performs with only 12 at a time. They perform often throughout the school year for senior centers, Rotary Clubs, US Senators and Delaware&#39;s governor. Last year, they were the featured performers at the National School Board Association&#39;s annual conference in Boston.
Many of the students in the choir were also in the school&#39;s Spring Musical - The 25th Annual Putnam County Spelling Bee - which closed last weekend. The JazzChords are pleased that the schedule allowed them to participate in the Roxbury Choir Invitational again this year because it is always a highlight of the school year for us.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[32,'CD Chanson','CDC',11,'John Madas','CD Chanson is the premier SSAA Womenâ€™s Choir at Central Dauphin High School. There are typically 30-35 young women in the ensemble. This one credit class meets everyday of the school year during period one, for 41 minutes. The ladies of CD Chanson learn challenging traditional and contemporary choral compositions, spanning all compositional time periods. Members of CD Chanson are expected to give extra time in order to contribute to the ensembleâ€™s artistic success. CD Chanson is a traveling choir, with the members performing at competitions and festivals, in addition to the four main choir performances of Fall, Holiday, Midwinter, and Spring. Additionally, members of CD Chanson perform as part of the annual CDSD District Honor Choir Festival. CD Chanson members learn advanced notation comprehension, score analysis, advanced solfege-hand sign command, rhythmic identification, advanced music theory elements, and foreign language pronunciation skills. Members of CD Chanson are examples of the choir philosophy: Artistry and Leadership Through Vocal Music Excellence. CD Chanson is an auditioned ensemble, open to sophomore, junior, and senior women.','1518461816.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[33,'River Dell High School Select Choir','RDHSSC',10,'Director Name','The River Dell High School Select Choir is an auditioned group that rehearses within the River Dell High School schedule serving students from both Oradell and River Edge, New Jersey.  This Select Choir performs at special community events and festivals, as well as at the semi-annual River Dell High School concerts and graduation.  Students in this choir regularly participate in County, Regional, and All-State ensembles. The ensemble is very excited to participate in and experience the Roxbury Invitational again.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[34,'Long Island Voices','LIV',13,'Jimmy Nagle','The Long Island Voices are a show choir from Connetquot High School in Bohemia, New York. The group performs a wide variety of music including musical theatre, contemporary a cappella, and vocal jazz. The group performs throughout Long Island for various school functions, community events, festivals, and competitions. Tonight, we will be performing selections from The Greatest Showman. All of the choreography was created by the students. We are excited to watch and learn from the clinicians and other groups!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[36,'Easton Area High School Jazz Chorale','EAHSJC',11,'Director Name','Soprano: Ashley Keane, Shekinah Roy, Chloe Spranger, Riana Wilson
Alto: Grace Emin, Katrina Godek, Anna-Patrice Roberts, Samantha Zimmerman
Tenor: Carols Brown, Gaven Green, Joseph Mowad, John Villanueva
Bass: Justin DePhillipo, Mitchell Huscher, Chase Kratzer, Joseph Krausz','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[37,'Montgomery Vocal Jazz','MVJ',11,'Director Name','The MHS Vocal Jazz Ensemble is one of the 6 choirs of Montgomery Township High School, located in Skillman, New Jersey, just north of Princeton.  Now in its fourth year, MHS Vocal Jazz is the program&#39;s newest co-curricular ensemble and is an auditioned, balanced, mixed choir comprised of 16 students.  The ensemble rehearses outside of school 2 to 3 times a week and is engaged in numerous performances in school and the community throughout the year.  They are thrilled to have been invited to the Roxbury Choral Invitational.  MHS Vocal Jazz is under the direction of Mr. Jeffrey Woodworth.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[38,'New Providence High School Jazz Choir','NPHSJC',11,'Director Name','Enter your group\'s description as you want to see it in the program','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[39,'Wallkill Valley Voices','WVV',11,'Director Name','The Wallkill Valley Voices is an auditioned group that meets once a week to learn about Jazz Music.  They are excited to be at the Roxbury Choir Invitational and wish all the other choirs the best of luck on this day!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[40,'CD Singers','CDS',10,'John Madas','The CD Singers of Central Dauphin High School serve as the premier SATB vocal ensemble at Central Dauphin High School. There are typically 40-45 members in CD Singers. This one credit class meets everyday of the school year during period three, for 41 minutes. The CD Singers learn challenging traditional and contemporary choral compositions, spanning all compositional time periods.  Members of CD Singers are expected to give extensive energy during and outside of the rehearsal setting. Daily practice of the repertoire is mandatory. This ensemble develops the highest level of vocal education, musicianship, and artistry. All members can be relied on as leaders, musically and personally. The CD Singers are a tour ensemble, performing at community events, off-site concerts, collaborations with other choirs, and competitive festivals in addition to the four CDHS-school concerts and the CDSD District Honors Festival. Members of CD Singers learn advanced notation comprehension, score analysis, advanced solfege-hand sign command, rhythmic identification, advanced music theory elements, and foreign language pronunciation skills. The CD Singers are living examples of the choir philosophy: Artistry and Leadership Through Vocal Music Excellence. This ensemble is an auditioned ensemble, open to sophomore, junior, and senior women and men.','1518462301.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[41,'A Cappella Choir','ACC',10,'Director Name','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[52,'Concert Choir','CC',10,'Director Name','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[56,'Easton Area High School Jazz Chorale','EAHSJC',11,'John P. Shilanskas','The EAHS Jazz Chorale is an auditioned SATB ensemble available to all EAHS students enrolled in Freshman Choir and Concert Choir. The ensemble performs vocal jazz music, typically with a jazz combo. The Jazz Chorale performs at various school and community events throughout the school year. We are excited the Roxbury Invitational is back and want to thank everyone at Roxbury High School for their warm hospitality.  Good luck to everyone performing today and best of luck in the future!','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[57,'Vocal Ensemble','VE',12,'Adam Speakman','Having toured throughout The United States and Europe these exceptional young artists from Downingtown, Pennsylvania have acquired an international reputation for excellence. They often sing at Philadelphia professional sporting events, as well as at many local community service performances. Their versatile repertoire ranges from classical to vocal jazz and pop. Many of our individual students have represented us at Districts, Regions, All-States, All-Eastern, and All-National festivals. The Downingtown East Vocal Ensemble was awarded first place with a superior rating at Festivals of Music competition (New York, 2007 and Washington, D.C., 2011). They have also won the Best Overall Choir Award at Music in the Parks: Hersheypark (2010, 2012, 2014, and 2016). Most recently, they received a Gold Rating at the Roxbury Choral Invitational in 2019, when they were also selected as an evening showcase finalist.','1513954243.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[58,'Dover High School Concert Choir','DHSCC',10,'Director Name','This course is designed to provide vocal/choral training. Good vocal techniques and music fundamentals are stressed. A variety of literature including secular, sacred, popular and show music will be studied.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[59,'Masterworks Choir','MC',10,'Adam Speakman','The choral music program in Downingtown has a long history of traditions and performances that enrich the lives of its members. A wide range of vocal techniques are explored through the study of advanced a-cappella works from the Renaissance period to the present day. Comprehensive musicianship skills such as score analysis, sight-singing, and music theory are also emphasized. The group often hosts collegiate professors, university ensembles, and professional artists as guest lecturers and workshop/masterclass presenters. Recently, the choir has performed at Notre Dame Cathedral (2015) and in Carnegie Hall (2017). In competitions, they often garner first place, superior ratings, and special awards for student and staff leadership. Notable recognitions include a Superior rating and Best Overall Choir Award at the Festivals of Music Competition in Boston (2009) and New York (2013), a Gold rating and Sweepstakes Award for Total Program at the WorldStrides Heritage Competition in Nashville (2015), a Superior rating at Festival Disney (2018), and a Gold rating and Outstanding Achievement Award at the Roxbury Choral Invitational (2018). Most recently, they were invited to perform at the PMEA Annual Conference (2020 and 2022).','1513954793.png','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[60,'Rockbridge Academy Kantorei','RAK',10,'Director Name','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[61,'WMC Concert Choir','WMCCC',10,'Director Name','none','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[62,'Shacappella','S',12,'Director Name','Shacappella specializes in contemporary a cappella music. It is an auditioned group of about 20 members that meet once a week in the evening. It is made up of male and female voices and also features vocal percussion.  This group often performs at special school events needing entertainment as well as at school concerts throughout the year.','','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[63,'A New Jazzy Group','ANJG',11,'Director Name','none','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[66,'Madrigals','M',10,'Director Name','none','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[68,'Union High School Swing Choir','UHSSC',13,'Mr. Patrick B. Phillips','The Union High School Swing Choir is proud to present their 2020 show - The Greatest Showman.
Under the direction of Mr. Patrick B. Phillips, the Union High School Swing Choir is an extracurricular auditioned, mixed show choir with high-level choreography. This award-winning ensemble is an exhibition and competitive choir that performs at local events and venues, concerts, and competitions. Along with the other theatrical, instrumental, and choral ensembles at Union High School, the Swing Choir has been a point of pride for Union Township having won many awards from various competitions across the United States. The Union High School Swing Choir tours once per year to compete at regional competitions in varying US cities. This Spring, the choir will be traveling to Boston, MA to compete against other choirs from across the country. uhspac.com / Insta: @uhs.uhspac','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[69,'Concert Chorale','CC',10,'Gordon Kaslusky','The Mechanicsburg Area Senior High School Concert Chorale is a select mixed-voice ensemble open to 10-12 grade students who demonstrate a passion for choral singing and a commitment to excellence.','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[70,'Chorale','C',10,'Jessica  Pomeroy','Hackettstown\'s Chorale is a small group of auditioned Treble voices grades 9-12 that meets once a week to rehearse outside of school. They frequently perform a wide variety of music in and outside of the community.','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[71,'Golden Blues','GB',13,'David Stephenson, Star Graham, Leigh Watson','Since 1983, the Lexington High School Golden Blues show choir has performed for audiences all over the southern US including Alabama, Georgia, Tennessee, Virginia, and West Virginia. The 39-singer ensemble and 9-member band is directed by Dr. David Stephenson, Star Graham, and Leigh Watson. Choreographers for the group are Lexi Robson and Christopher Brewer.','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[72,'Concert Choir','CC',10,'David Stephenson','The Lexington High School Concert Choir has established a long-standing tradition of excellence over the past 40-plus years. They have consistently earned superior ratings at festivals in California, Florida, Georgia, Missouri, South Carolina, Tennessee, Virginia, and Toronto, Ontario. This 40-voice ensemble is the top auditioned mixed ensemble at LHS and is under the direction of Dr. David Stephenson.','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[73,'Jazz Chorus','JC',11,'Daniel Malloy','none','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[74,'E.O. Smith Chamber Singers','EOSCS',10,'Amanda Hanzlik','The E.O. Smith Chamber Singers have been selected as a performing/showcase ensemble at the 2020 ACDA Division Conference
(The American Choral Directors Association), in Rochester, New York,  March 5, 2020.
The Eastern Division of ACDA is comprised of 12 states.
13 choirs were chosen (through a blind audition process) as ensembles who exemplify excellence in the choral arts
and we are 1 of 3 high school choirs to receive this incredible honor.
Here is the official press release, via the ACDA East website.
The Chamber Singers are an extraordinary group of musicians and this kind of National-level honor is unique and rare.
Over the past 20 years, there have only been 6 other Connecticut Choirs represented at ACDA Division.','none','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[75,'Honors Concert Choir','HCC',10,'Adam Good','none','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
[76,'Chorale','C',10,'Kristen Markowski','none','NULL','','2022-09-01 14:56:56','2022-09-01 14:56:56'],
            ];
    }
}
