<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SchoolsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('schools')->delete();

        \DB::table('schools')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Algonquin Regional High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Atlee High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Bacon Academy',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Barnstable High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Barrington High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Bartlett High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Belmont High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            7 =>
            array (
                'id' => 8,
                'name' => 'Blake High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            8 =>
            array (
                'id' => 9,
                'name' => 'Boyertown High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'black,red,silver',
                'student_body' => 0,
            ),
            9 =>
            array (
                'id' => 10,
                'name' => 'Bridgewater-Raritan High School',
                'address_1' => '600 Garretson Rd',
                'address_2' => NULL,
                'city' => 'Bridgewater',
                'geostate_id' => 37,
                'postal_code' => '08807',
                'colors' => 'black,red,silver',
                'student_body' => 2902,
            ),
            10 =>
            array (
                'id' => 11,
                'name' => 'Burnt Hills-Ballston Lake High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            11 =>
            array (
                'id' => 12,
                'name' => 'Cab Calloway School of the Arts',
                'address_1' => '100 N. duPont Road',
                'address_2' => NULL,
                'city' => 'Wilmington',
                'geostate_id' => 10,
                'postal_code' => '19807',
                'colors' => 'silver,black,purple',
                'student_body' => 897,
            ),
            12 =>
            array (
                'id' => 13,
                'name' => 'Capital Voices in Perfection  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            13 =>
            array (
                'id' => 14,
                'name' => 'Carlisle High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            14 =>
            array (
                'id' => 15,
                'name' => 'Cedar Cliff',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            15 =>
            array (
                'id' => 16,
                'name' => 'Central Dauphin High School',
                'address_1' => '437 Piketown Road',
                'address_2' => NULL,
                'city' => 'Harrisburg',
                'geostate_id' => 44,
                'postal_code' => '17112',
                'colors' => 'white,green,none',
                'student_body' => 1696,
            ),
            16 =>
            array (
                'id' => 17,
                'name' => 'Central Islip High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            17 =>
            array (
                'id' => 18,
                'name' => 'Chantilly High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            18 =>
            array (
                'id' => 19,
                'name' => 'Cherry Hill East High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            19 =>
            array (
                'id' => 20,
                'name' => 'Cheshire High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            20 =>
            array (
                'id' => 21,
                'name' => 'Cheverus High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            21 =>
            array (
                'id' => 22,
                'name' => 'Clover Hill High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            22 =>
            array (
                'id' => 23,
                'name' => 'Coginchaug Regional High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            23 =>
            array (
                'id' => 24,
                'name' => 'Connetquot Central School District',
                'address_1' => '190 Seventh Street',
                'address_2' => NULL,
                'city' => 'Bohemia',
                'geostate_id' => 40,
                'postal_code' => '11716',
                'colors' => 'Red,Black,White',
                'student_body' => 28,
            ),
            24 =>
            array (
                'id' => 25,
                'name' => 'Dover High School',
                'address_1' => '100 Grace Street',
                'address_2' => NULL,
                'city' => 'Dover',
                'geostate_id' => 37,
                'postal_code' => '07801',
                'colors' => 'black,orange,none',
                'student_body' => 893,
            ),
            25 =>
            array (
                'id' => 26,
                'name' => 'Downingtown East High School',
                'address_1' => '50 Devon Drive',
                'address_2' => NULL,
                'city' => 'Exton',
                'geostate_id' => 44,
                'postal_code' => '19341',
                'colors' => 'blue,gold,',
                'student_body' => 1708,
            ),
            26 =>
            array (
                'id' => 27,
                'name' => 'East Brunswick High School',
                'address_1' => '380 Cranberry Road',
                'address_2' => NULL,
                'city' => 'East Brunswick',
                'geostate_id' => 37,
                'postal_code' => '08816',
                'colors' => 'white,green',
                'student_body' => 2077,
            ),
            27 =>
            array (
                'id' => 28,
                'name' => 'Easton Area High School',
                'address_1' => '2601 William Penn Highway',
                'address_2' => NULL,
                'city' => 'Easton',
                'geostate_id' => 44,
                'postal_code' => '18045',
                'colors' => 'Red,Black,White',
                'student_body' => 3218,
            ),
            28 =>
            array (
                'id' => 29,
                'name' => 'Egg Harbor Township High School ',
                'address_1' => '24 High School Drive',
                'address_2' => NULL,
                'city' => 'Egg Harbor Township',
                'geostate_id' => 37,
                'postal_code' => '08234',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            29 =>
            array (
                'id' => 30,
                'name' => 'Ellington High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            30 =>
            array (
                'id' => 31,
                'name' => 'Exeter Township High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            31 =>
            array (
                'id' => 32,
                'name' => 'Fox Chapel Area High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            32 =>
            array (
                'id' => 33,
                'name' => 'Glenwood High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            33 =>
            array (
                'id' => 34,
                'name' => 'Grove City High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            34 =>
            array (
                'id' => 35,
                'name' => 'Hackettstown High School',
                'address_1' => '599 Warren Street',
                'address_2' => NULL,
                'city' => 'Hackettstown',
                'geostate_id' => 37,
                'postal_code' => '07840',
                'colors' => 'black,orange,',
                'student_body' => 750,
            ),
            35 =>
            array (
                'id' => 36,
                'name' => 'Haddon Heights High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            36 =>
            array (
                'id' => 37,
                'name' => 'Hanover High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            37 =>
            array (
                'id' => 38,
                'name' => 'Hanover Park High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            38 =>
            array (
                'id' => 39,
                'name' => 'Herricks High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            39 =>
            array (
                'id' => 40,
                'name' => 'Hershey High School',
                'address_1' => '550 Homestead Road',
                'address_2' => NULL,
                'city' => 'Hersey',
                'geostate_id' => 44,
                'postal_code' => '17033',
                'colors' => 'blue,orange,',
                'student_body' => 1340,
            ),
            40 =>
            array (
                'id' => 41,
                'name' => 'Holton Arms Upper School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            41 =>
            array (
                'id' => 42,
                'name' => 'Hopewell Valley Central High School',
                'address_1' => '259 Pennington Titusville Road',
                'address_2' => NULL,
                'city' => 'Pennington',
                'geostate_id' => 37,
                'postal_code' => '08534',
                'colors' => 'Black,Gold,',
                'student_body' => 1100,
            ),
            42 =>
            array (
                'id' => 43,
                'name' => 'Howell High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            43 =>
            array (
                'id' => 44,
                'name' => 'J.P. Stevens High School',
                'address_1' => '855 Grove Ave',
                'address_2' => NULL,
                'city' => 'Edison',
                'geostate_id' => 37,
                'postal_code' => '08820',
                'colors' => 'Old gold,Dartmouth Green,',
                'student_body' => 2500,
            ),
            44 =>
            array (
                'id' => 45,
                'name' => 'James River High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            45 =>
            array (
                'id' => 46,
                'name' => 'JFK High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            46 =>
            array (
                'id' => 47,
                'name' => 'Kettering Fairmont High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            47 =>
            array (
                'id' => 48,
                'name' => 'Lebanon High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            48 =>
            array (
                'id' => 49,
                'name' => 'Ledyard High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            49 =>
            array (
                'id' => 50,
                'name' => 'Lee-Davis High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            50 =>
            array (
                'id' => 51,
                'name' => 'Lehighton Area High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            51 =>
            array (
                'id' => 52,
                'name' => 'Lower Dauphin High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            52 =>
            array (
                'id' => 53,
                'name' => 'Loyalsock High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            53 =>
            array (
                'id' => 54,
                'name' => 'Mamaroneck High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            54 =>
            array (
                'id' => 55,
                'name' => 'Manchester High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            55 =>
            array (
                'id' => 56,
                'name' => 'Marriotts Ridge High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            56 =>
            array (
                'id' => 57,
                'name' => 'Martinsburg High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            57 =>
            array (
                'id' => 58,
                'name' => 'Middletown High School NJ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            58 =>
            array (
                'id' => 59,
                'name' => 'Middletown High School PA',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            59 =>
            array (
                'id' => 60,
                'name' => 'Midlothian High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            60 =>
            array (
                'id' => 61,
                'name' => 'Millburn High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            61 =>
            array (
                'id' => 62,
                'name' => 'Miller Place High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            62 =>
            array (
                'id' => 63,
                'name' => 'Monacan High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            63 =>
            array (
                'id' => 64,
                'name' => 'Monroe Township High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            64 =>
            array (
                'id' => 65,
                'name' => 'Monsignor Donovan High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            65 =>
            array (
                'id' => 66,
                'name' => 'Montgomery Township High School',
                'address_1' => '1016 Route 601',
                'address_2' => NULL,
                'city' => 'Skillman',
                'geostate_id' => 37,
                'postal_code' => '08558',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            66 =>
            array (
                'id' => 68,
                'name' => 'Montville High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            67 =>
            array (
                'id' => 70,
                'name' => 'Morristown High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            68 =>
            array (
                'id' => 71,
                'name' => 'Mount Olive High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            69 =>
            array (
                'id' => 72,
                'name' => 'New Providence High School',
                'address_1' => '100 North Dupont Road',
                'address_2' => NULL,
                'city' => 'Wilmington',
                'geostate_id' => 10,
                'postal_code' => '19805',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            70 =>
            array (
                'id' => 74,
                'name' => 'Newark Academy',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            71 =>
            array (
                'id' => 75,
                'name' => 'Niskayuna High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            72 =>
            array (
                'id' => 76,
                'name' => 'Norwood High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            73 =>
            array (
                'id' => 77,
                'name' => 'Oakland Mills High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            74 =>
            array (
                'id' => 78,
                'name' => 'Oliver Ames High School',
                'address_1' => '100 Lothrop Street',
                'address_2' => NULL,
                'city' => 'North Easton',
                'geostate_id' => 23,
                'postal_code' => '02356',
                'colors' => 'black,orange',
                'student_body' => 1189,
            ),
            75 =>
            array (
                'id' => 79,
                'name' => 'Onteora High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            76 =>
            array (
                'id' => 80,
                'name' => 'Patapsco High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            77 =>
            array (
                'id' => 81,
                'name' => 'Peabody High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            78 =>
            array (
                'id' => 82,
                'name' => 'Perryville High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            79 =>
            array (
                'id' => 83,
                'name' => 'Point Pleasant High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            80 =>
            array (
                'id' => 84,
                'name' => 'Port Allegany High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            81 =>
            array (
                'id' => 85,
                'name' => 'Randolph High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            82 =>
            array (
                'id' => 86,
                'name' => 'Ridge High School',
                'address_1' => 'South Finley Avenue',
                'address_2' => NULL,
                'city' => 'Basking Ridge',
                'geostate_id' => 37,
                'postal_code' => '07924',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            83 =>
            array (
                'id' => 87,
                'name' => 'River Dell High School',
                'address_1' => '55 Pyle St',
                'address_2' => NULL,
                'city' => 'Oradell',
                'geostate_id' => 37,
                'postal_code' => '07649',
                'colors' => 'Black,Gold,',
                'student_body' => 1000,
            ),
            84 =>
            array (
                'id' => 88,
                'name' => 'Rockbridge Academy',
                'address_1' => '911 Generals Hwy',
                'address_2' => NULL,
                'city' => 'Millersville',
                'geostate_id' => 24,
                'postal_code' => '21108',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            85 =>
            array (
                'id' => 89,
                'name' => 'Roxbury High School',
                'address_1' => '1 Bryant Drive',
                'address_2' => '',
                'city' => 'Succasunna',
                'geostate_id' => 37,
                'postal_code' => '07876',
                'colors' => 'Blue,Gold,',
                'student_body' => 1400,
            ),
            86 =>
            array (
                'id' => 92,
                'name' => 'Sayville High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            87 =>
            array (
                'id' => 93,
                'name' => 'Seneca High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            88 =>
            array (
                'id' => 94,
                'name' => 'Shawnee High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            89 =>
            array (
                'id' => 95,
                'name' => 'Somerset High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            90 =>
            array (
                'id' => 96,
                'name' => 'South Windsor High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            91 =>
            array (
                'id' => 97,
                'name' => 'Sparta High School',
                'address_1' => '70 W Mountain Rd',
                'address_2' => NULL,
                'city' => 'Sparta Township',
                'geostate_id' => 37,
                'postal_code' => '07871',
                'colors' => 'Blue,White,',
                'student_body' => 1142,
            ),
            92 =>
            array (
                'id' => 98,
                'name' => 'Spencerport High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            93 =>
            array (
                'id' => 99,
                'name' => 'State College Area High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            94 =>
            array (
                'id' => 100,
                'name' => 'Sterling High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'white,royal blue,silver',
                'student_body' => 961,
            ),
            95 =>
            array (
                'id' => 101,
                'name' => 'Stoughton High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            96 =>
            array (
                'id' => 102,
                'name' => 'Summit High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            97 =>
            array (
                'id' => 103,
                'name' => 'Susquenita High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            98 =>
            array (
                'id' => 104,
                'name' => 'Tenafly High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            99 =>
            array (
                'id' => 105,
                'name' => 'The Pennington School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            100 =>
            array (
                'id' => 106,
                'name' => 'The Stony Brook School',
                'address_1' => '1 Chapman Parkway',
                'address_2' => NULL,
                'city' => 'Stony Brook',
                'geostate_id' => 40,
                'postal_code' => '11790',
                'colors' => 'Navy Blue,White,',
                'student_body' => 400,
            ),
            101 =>
            array (
                'id' => 107,
                'name' => 'Vernon Township High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            102 =>
            array (
                'id' => 108,
                'name' => 'Verona High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            103 =>
            array (
                'id' => 109,
                'name' => 'Voorhees High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            104 =>
            array (
                'id' => 110,
                'name' => 'Wallkill Valley Regional High School',
                'address_1' => '10 Grumm Road',
                'address_2' => NULL,
                'city' => 'Hamburg',
                'geostate_id' => 37,
                'postal_code' => '07419',
                'colors' => 'black,white,silver',
                'student_body' => 577,
            ),
            105 =>
            array (
                'id' => 111,
                'name' => 'Walter Johnson High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            106 =>
            array (
                'id' => 112,
                'name' => 'Waltham High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            107 =>
            array (
                'id' => 113,
                'name' => 'Ward Melville High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            108 =>
            array (
                'id' => 114,
                'name' => 'Warren Hills Regional High School',
                'address_1' => '41 Jackson Valley Rd',
                'address_2' => NULL,
                'city' => 'Washington',
                'geostate_id' => 37,
                'postal_code' => '07882',
                'colors' => 'Blue,White,',
                'student_body' => 1300,
            ),
            109 =>
            array (
                'id' => 115,
                'name' => 'Warwick High School  ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            110 =>
            array (
                'id' => 116,
                'name' => 'West Milford High School',
                'address_1' => '67 Highlander Drive',
                'address_2' => NULL,
                'city' => 'West Milford',
                'geostate_id' => 37,
                'postal_code' => '07480',
                'colors' => 'Black,Gold,',
                'student_body' => 1175,
            ),
            111 =>
            array (
                'id' => 117,
                'name' => 'West Morris Central High School',
                'address_1' => '259 Bartley Road',
                'address_2' => NULL,
                'city' => 'Chester',
                'geostate_id' => 37,
                'postal_code' => '07930',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            112 =>
            array (
                'id' => 118,
                'name' => 'Westwood Regional High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            113 =>
            array (
                'id' => 119,
                'name' => 'Williamsport High School ',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            114 =>
            array (
                'id' => 120,
                'name' => 'FJR Academy of Arts',
                'address_1' => '70 W Mountain Rd',
                'address_2' => NULL,
                'city' => 'Sparta Township',
                'geostate_id' => 37,
                'postal_code' => '07871',
                'colors' => 'none,none,none',
                'student_body' => 1,
            ),
            115 =>
            array (
                'id' => 121,
                'name' => 'Winston Churchill High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            116 =>
            array (
                'id' => 122,
                'name' => 'Woodbridge High School',
                'address_1' => 'Address 1',
                'address_2' => NULL,
                'city' => 'City',
                'geostate_id' => 37,
                'postal_code' => '12345-6789',
                'colors' => 'none,none,none',
                'student_body' => 0,
            ),
            117 =>
            array (
                'id' => 123,
                'name' => 'Lenape High School',
                'address_1' => '235 Hartford Road',
                'address_2' => NULL,
                'city' => 'Medford',
                'geostate_id' => 37,
                'postal_code' => '08055',
                'colors' => 'none,none,none',
                'student_body' => 1,
            ),
            118 =>
            array (
                'id' => 124,
                'name' => 'Wilton High School',
                'address_1' => '395 Danbury Road',
                'address_2' => NULL,
                'city' => 'Wilton',
                'geostate_id' => 8,
                'postal_code' => '06897',
                'colors' => 'Blue,White',
                'student_body' => 1,
            ),
            119 =>
            array (
                'id' => 125,
                'name' => 'Union High School',
                'address_1' => '2350 North 3rd Street',
                'address_2' => NULL,
                'city' => 'Union',
                'geostate_id' => 37,
                'postal_code' => '07083',
                'colors' => 'Maroon,Gold,White',
                'student_body' => 2212,
            ),
            120 =>
            array (
                'id' => 126,
                'name' => 'Mechanicsburg Area Senior High School',
                'address_1' => '500 South Broad Street',
                'address_2' => NULL,
                'city' => 'Mechanicsburg',
                'geostate_id' => 44,
                'postal_code' => '17055',
            'colors' => 'Maroon,Steel (gray),',
                'student_body' => 1200,
            ),
            121 =>
            array (
                'id' => 127,
                'name' => 'Lexington High School',
                'address_1' => '2463 Augusta Highway',
                'address_2' => NULL,
                'city' => 'Lexington',
                'geostate_id' => 48,
                'postal_code' => '29072',
                'colors' => 'Blue,Gold,',
                'student_body' => 2200,
            ),
            122 =>
            array (
                'id' => 128,
                'name' => 'Madison High School',
                'address_1' => '170 Ridgedale Avenue',
                'address_2' => NULL,
                'city' => 'Madison',
                'geostate_id' => 37,
                'postal_code' => '07940',
                'colors' => 'White,Maroon,Gold',
                'student_body' => 837,
            ),
            123 =>
            array (
                'id' => 129,
                'name' => 'Edwin O. Smith High School',
                'address_1' => '1235 Storrs Road',
                'address_2' => 'University of Connecticut',
                'city' => 'Storrs-Mansfield',
                'geostate_id' => 8,
                'postal_code' => '06268',
                'colors' => 'red, black',
                'student_body' => 1137,
            ),
            124 =>
            array (
                'id' => 130,
                'name' => 'Morris Knolls High School',
                'address_1' => '50 Knoll Drive',
                'address_2' => NULL,
                'city' => 'Rockaway',
                'geostate_id' => 37,
                'postal_code' => '07866',
                'colors' => 'Green,Gold,',
                'student_body' => 1279,
            ),
        ));


    }
}
