<?php

namespace Database\Seeders;

use App\Models\Role;
use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Rick Retzko',
                'first' => 'Rick',
                'middle' => NULL,
                'last' => 'Retzko',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'rick@mfrholdings.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jP6Jvt81O0iN..1DuvMhCO.mkIMQMduYMHpZPVOjaVsLJ/TDjTSMW',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Amy Collins',
                'first' => 'Amy',
                'middle' => NULL,
                'last' => 'Collins',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'Acollins@nsboro.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$jh./hlhqLLeu2Yv6pfyYHOankwVKJojiRDiQffPIA8RdodmY36Sya',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Natan Berenshteyn',
                'first' => 'Natan',
                'middle' => NULL,
                'last' => 'Berenshteyn',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'nberenshteyn@hanover.k12.va.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$nYYGGaJQynEaQSITlE14VeulgQEHkvgGpzORZHldx7jounKSYXnXm',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Marinne Cheney',
                'first' => 'Marinne',
                'middle' => NULL,
                'last' => 'Cheney',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mcheney@colchesterct.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$W8vyjmSJunEapKSrWbylhOgQF/cpbDU3.eCMmHA4vnVlNBTb0si82',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            4 =>
            array (
                'id' => 6,
                'name' => 'Celeste Labonte',
                'first' => 'Celeste',
                'middle' => NULL,
                'last' => 'Labonte',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'labontec@barringtonschools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$SZwc1WpWuNfkiN5krER2rOO7KPMWriEiARKnYnXR2vbTnLGfaVMue',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            5 =>
            array (
                'id' => 7,
                'name' => 'Pete Carney',
                'first' => 'Pete',
                'middle' => NULL,
                'last' => 'Carney',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'pcarney@webster-schools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$imsOnK2wdxNE/2mcVv1woeh0qFT2E/CsiDIiyuwcZCmB3B6lVzXoS',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            6 =>
            array (
                'id' => 8,
                'name' => 'Sean Landers',
                'first' => 'Sean',
                'middle' => NULL,
                'last' => 'Landers',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'slanders@belmont.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eoHQmdN28mdlZIkQKuL2TeRRtgdayZIUu0vawCjLRSsfD0Ncsyk0.',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            7 =>
            array (
                'id' => 10,
                'name' => 'Jeffrey Brunner',
                'first' => 'Jeffrey',
                'middle' => NULL,
                'last' => 'Brunner',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jbrunner@boyertownasd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$w3pZt76H66RcesZb5NSYTukvKBEgMIHzhx46MnteBYqzBxE3KSBZK',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            8 =>
            array (
                'id' => 12,
                'name' => 'Ann Derrick',
                'first' => 'Ann',
                'middle' => NULL,
                'last' => 'Derrick',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'aderrick@bhbl.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$s/LH6K/7WSpY.jOc5RZaDed884l90EBbCRGkF95K39CHQitw.CnNO',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            9 =>
            array (
                'id' => 13,
                'name' => 'Martin Lassman',
                'first' => 'Martin',
                'middle' => NULL,
                'last' => 'Lassman',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'martin.lassman@redclay.k12.de.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ne9uxfseDPs9Rn6FZ.xIyOyQId0WyuYcgVQ87z7pmdFo/LVwfWnTK',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            10 =>
            array (
                'id' => 14,
                'name' => 'Kathleen Corbett',
                'first' => 'Kathleen',
                'middle' => NULL,
                'last' => 'Corbett',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kcorbett@kcs.kana.k12.wv.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$zgWvZTK9izQfGr8db6uwAeKgi0h3.qawiDx.vSQBKBhEBy8ZNlL1G',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            11 =>
            array (
                'id' => 15,
                'name' => 'Dan Schade',
                'first' => 'Dan',
                'middle' => NULL,
                'last' => 'Schade',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'Schade@carlisleschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            12 =>
            array (
                'id' => 16,
                'name' => 'Matthew Topping',
                'first' => 'Matthew',
                'middle' => NULL,
                'last' => 'Topping',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mtopping@wssd.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            13 =>
            array (
                'id' => 17,
                'name' => 'John L. Madas',
                'first' => 'John',
                'middle' => 'L.',
                'last' => 'Madas',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'johnmadas@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$cuistWL6fNVQZxMMPFFDueooUcHGEIGwdWqHVLvwXtucR9KiijOBS',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            14 =>
            array (
                'id' => 18,
                'name' => 'John Anthony',
                'first' => 'John',
                'middle' => NULL,
                'last' => 'Anthony',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'janthony@cischools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dRiOKVt6gN11MTd8ApczNOe9pTC.tcuNlDlUzC9QZTZxAZhy6QUfG',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            15 =>
            array (
                'id' => 19,
                'name' => 'Evan Ayars',
                'first' => 'Evan',
                'middle' => NULL,
                'last' => 'Ayars',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'EMAyars@fcps.edu',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZBIzQ.VtHZt5AD4jtfg6Xe7p0Sr.G77vghFTt3fnIRk4QqQ62Vhrq',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            16 =>
            array (
                'id' => 20,
                'name' => 'Heather Frampton',
                'first' => 'Heather',
                'middle' => NULL,
                'last' => 'Frampton',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'hframpton@chclc.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZVF.cUS2rR0DnSes5EJeWOd8M53bueZaqy6rGl4l.WrpKESztK2RC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            17 =>
            array (
                'id' => 21,
                'name' => 'Laurie Lausi',
                'first' => 'Laurie',
                'middle' => NULL,
                'last' => 'Lausi',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'notes2lausi@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$sHGGLk.wIIo.fo8pqMfCg.9Hdd7/wFsdcQzLLMeioqpb8nsRx3qrW',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            18 =>
            array (
                'id' => 22,
                'name' => 'Heather Lockart',
                'first' => 'Heather',
                'middle' => NULL,
                'last' => 'Lockart',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'hlockart@chclc.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$H.cLovOfYeAru.5FYdrLtO3sh5nvRdX.mwreRSRLFs/dA6Zmo5kx6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            19 =>
            array (
                'id' => 23,
                'name' => 'Beth Rosenblatt',
                'first' => 'Beth',
                'middle' => NULL,
                'last' => 'Rosenblatt',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'brosenblatt@cheshirect.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            20 =>
            array (
                'id' => 24,
                'name' => 'Chris Humphrey',
                'first' => 'Chris',
                'middle' => NULL,
                'last' => 'Humphrey',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'humphrey@cheverus.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3D1wo4Rf6lGU4IdYtLTj8uJzTc1SffA9xys4Dq6KvzsNMmLcU35ze',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            21 =>
            array (
                'id' => 25,
                'name' => 'Sandra Thomas',
                'first' => 'Sandra',
                'middle' => NULL,
                'last' => 'Thomas',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'sandra_thomas@ccpsnet.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            22 =>
            array (
                'id' => 26,
                'name' => 'Erin Schilling',
                'first' => 'Erin',
                'middle' => NULL,
                'last' => 'Schilling',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'eschilling@rsd13.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            23 =>
            array (
                'id' => 27,
                'name' => 'James Nagle',
                'first' => 'James',
                'middle' => NULL,
                'last' => 'Nagle',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'JNagle@ccsdli.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            24 =>
            array (
                'id' => 28,
                'name' => 'Jack Hoferer',
                'first' => 'Jack',
                'middle' => NULL,
                'last' => 'Hoferer',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jhoferer@dover-nj.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$fYGUq0UbgtQVQ8gE8yN9OusomJYiSkMFInNcwtqMLuTY3Jw6MbWIO',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            25 =>
            array (
                'id' => 29,
                'name' => 'Adam Speakman',
                'first' => 'Adam',
                'middle' => NULL,
                'last' => 'Speakman',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'aspeakman@dasd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            26 =>
            array (
                'id' => 31,
                'name' => 'John Paul Shilanskas',
                'first' => 'John Paul',
                'middle' => NULL,
                'last' => 'Shilanskas',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'shilanskasj@eastonsd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            27 =>
            array (
                'id' => 33,
                'name' => 'Richard Diamond',
                'first' => 'Richard',
                'middle' => NULL,
                'last' => 'Diamond',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'rdiamond@ellingtonschools.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dTWkf5XKZhCT.6nnZPnpp.hSmMZsOz.yP.tB0TgEN90dHVwZ9oCum',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            28 =>
            array (
                'id' => 34,
                'name' => 'Elizabeth Heck',
                'first' => 'Elizabeth',
                'middle' => NULL,
                'last' => 'Heck',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'eaheck@exeter.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$x5oJBXSPHR5o4IZBMGcJguzKxgImnaZNLHC4e3ZNNs8CCEypgAdgK',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            29 =>
            array (
                'id' => 35,
                'name' => 'Ben Murray',
                'first' => 'Ben',
                'middle' => NULL,
                'last' => 'Murray',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'Ben_Murray@fcasd.ed',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            30 =>
            array (
                'id' => 36,
                'name' => 'Jeff Gemar',
                'first' => 'Jeff',
                'middle' => NULL,
                'last' => 'Gemar',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jgemar@bcsd5.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$f6eLE3.kkEm8Z1LwQWl6V./esWHxU7chx7H4R10esZqUxAPNkaBU.',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            31 =>
            array (
                'id' => 37,
                'name' => 'Hannah Jaskiewicz',
                'first' => 'Hannah',
                'middle' => NULL,
                'last' => 'Jaskiewicz',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jaskiewicz@grovecity.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ierbJLBqqsnnDbXUQyYbsO3EL2zsrXhFaah6vgo9BgcTksvNGOJ.G',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            32 =>
            array (
                'id' => 38,
                'name' => 'Jessica Pomeroy',
                'first' => 'Jessica',
                'middle' => NULL,
                'last' => 'Pomeroy',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jpomeroy@hackettstown.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            33 =>
            array (
                'id' => 39,
                'name' => 'Christine Walker',
                'first' => 'Christine',
                'middle' => NULL,
                'last' => 'Walker',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'walkerc@hhsd.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            34 =>
            array (
                'id' => 40,
                'name' => 'James Barrack',
                'first' => 'James',
                'middle' => NULL,
                'last' => 'Barrack',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jbarrack@hcps.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$d0PTanrc6U0f7mH8X0a7zesIU6DEXfcSoDCE1u9hH72twvf/qYncS',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            35 =>
            array (
                'id' => 41,
                'name' => 'Helen Ferrante de Britez',
                'first' => 'Helen',
                'middle' => NULL,
                'last' => 'Ferrante de Britez',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'hbritez@hpreg.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$J4/0sx8lgM3Sb.VeIg72MuHXcHku8qpC6sgdRy74rqGn7kaW29n0C',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            36 =>
            array (
                'id' => 42,
                'name' => 'Louise OHanlon',
                'first' => 'Louise',
                'middle' => NULL,
                'last' => 'OHanlon',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'louiselej@aol.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            37 =>
            array (
                'id' => 43,
                'name' => 'Joseph Farrell',
                'first' => 'Joseph',
                'middle' => NULL,
                'last' => 'Farrell',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jfarrell@hershey.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$XyVeCiE7Cjkij7oD/fjCJeTYifdAqEjNs9BZ9OjPN.At6i8d9wcHO',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            38 =>
            array (
                'id' => 44,
                'name' => 'MaryJane Pagenstecher',
                'first' => 'MaryJane',
                'middle' => NULL,
                'last' => 'Pagenstecher',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'MaryJane.Pagenstecher@holton-arms.edu',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            39 =>
            array (
                'id' => 46,
                'name' => 'Joe Cantaffa',
                'first' => 'Joe',
                'middle' => NULL,
                'last' => 'Cantaffa',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jcantaffahhs@hotmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$nvGoamS0LUNshg9PBWGXAulz130n9MskV5x1JR25VlF7dNhofpoVi',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            40 =>
            array (
                'id' => 47,
                'name' => 'Matthew Lee',
                'first' => 'Matthew',
                'middle' => NULL,
                'last' => 'Lee',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'matthew.lee@edison.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Eeic80DdF4ByJa/3JHeEB.OQIwQ2pMZpesZ1oAkLiO8CT/2SPvO9m',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            41 =>
            array (
                'id' => 48,
                'name' => 'Marissa Parsons',
                'first' => 'Marissa',
                'middle' => NULL,
                'last' => 'Parsons',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'marrisa_parsons@ccpsnet.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            42 =>
            array (
                'id' => 49,
                'name' => 'Christine Scott',
                'first' => 'Christine',
                'middle' => NULL,
                'last' => 'Scott',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'christine.scott@woodbridge.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            43 =>
            array (
                'id' => 50,
                'name' => 'Brody McDonald',
                'first' => 'Brody',
                'middle' => NULL,
                'last' => 'McDonald',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'brody.mcdonald@ketteringschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            44 =>
            array (
                'id' => 51,
                'name' => 'Mark Naimoli',
                'first' => 'Mark',
                'middle' => NULL,
                'last' => 'Naimoli',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mnaimoli@lebanon.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            45 =>
            array (
                'id' => 52,
                'name' => 'Melanie Cometa',
                'first' => 'Melanie',
                'middle' => NULL,
                'last' => 'Cometa',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mcometa@ledyard.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$7fhiJS0CywZtDxFpZRO7eOn0ykZRMajTMRyS0fyuMR0LprpTNplC6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            46 =>
            array (
                'id' => 53,
                'name' => 'Megan Cartwright',
                'first' => 'Megan',
                'middle' => NULL,
                'last' => 'Cartwright',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mcartwright@hanover.k12.va.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MVn0Y5OjdwEcFCPT2bOKIedL.jK8xXOaixtrhqQgj6WpV7vGIZ2r6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            47 =>
            array (
                'id' => 54,
                'name' => 'David Perkins',
                'first' => 'David',
                'middle' => NULL,
                'last' => 'Perkins',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'perkdb@ptd.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            48 =>
            array (
                'id' => 55,
                'name' => 'Elizabeth Colpo',
                'first' => 'Elizabeth',
                'middle' => NULL,
                'last' => 'Colpo',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'ecolpo@ldsd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VxoxWLjdK4Zq7Otr87vdc.AJtPj2aVDBbYeSe.3RBRBjxUkX3tX4e',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            49 =>
            array (
                'id' => 56,
                'name' => 'Lee Saville-Iksic',
                'first' => 'Lee',
                'middle' => NULL,
                'last' => 'Saville-Iksic',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'lsavilleandree@loyalsocklancers.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            50 =>
            array (
                'id' => 57,
                'name' => 'Dina Madden',
                'first' => 'Dina',
                'middle' => NULL,
                'last' => 'Madden',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'dmadden@mamkschools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RDijWbV.OUR4uSoe7NDdEOrVvIpjhOO9HX6aHLo5AnY/hNE4YvExm',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            51 =>
            array (
                'id' => 58,
                'name' => 'Robyn Kim',
                'first' => 'Robyn',
                'middle' => NULL,
                'last' => 'Kim',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'robyn_kim@ccpsnet.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$2JEgX9uGUClyZ5ayUEwieOvMEQSeE9Cr5eEeTBSO9Fys4pJpGPC5q',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            52 =>
            array (
                'id' => 59,
                'name' => 'Scott Aucoin',
                'first' => 'Scott',
                'middle' => NULL,
                'last' => 'Aucoin',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'scott_aucoin@hcpss.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$WtTDhxad5qHgTQhKXjztcu8YnfVQzncPQXXk97y/8dVIBPBxo1D2q',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            53 =>
            array (
                'id' => 60,
                'name' => 'Kathie Smith',
                'first' => 'Kathie',
                'middle' => NULL,
                'last' => 'Smith',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'k.m.smith@access.k12.wv.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            54 =>
            array (
                'id' => 61,
                'name' => 'Peter Isherwood',
                'first' => 'Peter',
                'middle' => NULL,
                'last' => 'Isherwood',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'Isherwoodp@middletownk12.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$iHeOACCUwC5W4ewGtVau..lMR1WhTVbOB9Sefc.1UtCPW05kBpk.u',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            55 =>
            array (
                'id' => 62,
                'name' => 'Andrew Vensel',
                'first' => 'Andrew',
                'middle' => NULL,
                'last' => 'Vensel',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'avensel@raiderweb.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            56 =>
            array (
                'id' => 63,
                'name' => 'Michelle Graham',
                'first' => 'Michelle',
                'middle' => NULL,
                'last' => 'Graham',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'michelle_graham@ccpsnet.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$b1GyfM06R8h7sFILK2SgPu6vagixJf1gERUFxP9vfJ/8UWJ0bBwf6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            57 =>
            array (
                'id' => 64,
                'name' => 'Jessica Pierce',
                'first' => 'Jessica',
                'middle' => NULL,
                'last' => 'Pierce',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jessica.peirce@millburn.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            58 =>
            array (
                'id' => 65,
                'name' => 'MaryJean Stead',
                'first' => 'MaryJean',
                'middle' => NULL,
                'last' => 'Stead',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'tstead@aol.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            59 =>
            array (
                'id' => 66,
                'name' => 'Nathan Miller',
                'first' => 'Nathan',
                'middle' => NULL,
                'last' => 'Miller',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'nathan_miller@ccpsnet.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            60 =>
            array (
                'id' => 67,
                'name' => 'Arielle Klein',
                'first' => 'Arielle',
                'middle' => NULL,
                'last' => 'Klein',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'arielle.klein@monroe.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$yLkNmpgQILZorawM77NOmu8BmFCkGRm46cfmreLE5hdYCvA6axR4y',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            61 =>
            array (
                'id' => 68,
                'name' => 'Cindy Wald',
                'first' => 'Cindy',
                'middle' => NULL,
                'last' => 'Wald',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cwald@mondonhs.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            62 =>
            array (
                'id' => 69,
                'name' => 'Neelam Makvana',
                'first' => 'Neelam',
                'middle' => NULL,
                'last' => 'Makvana',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'nmakvana@mtsd.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$x2QG.xGJQE8D0.DfTwKhU..RGYfefB5tLHXpb3ui8zbnsSS8GvVcC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            63 =>
            array (
                'id' => 71,
                'name' => 'Joshua Cushing',
                'first' => 'Joshua',
                'middle' => NULL,
                'last' => 'Cushing',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'joshua.cushing@montville.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$LAwjVxHynGry1ZLCv69qfObkugpS.r1VVjJ/Tyi/VA1YoKP8RZ5ri',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            64 =>
            array (
                'id' => 72,
                'name' => 'Michael Nuzzo',
                'first' => 'Michael',
                'middle' => NULL,
                'last' => 'Nuzzo',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'michael.nuzzo@morristownhighschool.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            65 =>
            array (
                'id' => 73,
                'name' => 'Matthew Vanzini',
                'first' => 'Matthew',
                'middle' => NULL,
                'last' => 'Vanzini',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mvanzini@mtoliveboe.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            66 =>
            array (
                'id' => 74,
                'name' => 'Susan Kirkland',
                'first' => 'Susan',
                'middle' => NULL,
                'last' => 'Kirkland',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'skirkland@npsdnj.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$RyKNb9JM3yowmiPkA7XJzO4DH5AfldWfp2MI28PrSxI2HePjnoccy',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            67 =>
            array (
                'id' => 76,
                'name' => 'Viraj Lal',
                'first' => 'Viraj',
                'middle' => NULL,
                'last' => 'Lal',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'vlal@newark.edu',
                'email_verified_at' => NULL,
                'password' => '$2y$10$E4SC3L7Cz9tPORF.P6lNMeXw7kWNjOTuJRZuO5O26HKbisp0m/Ez6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            68 =>
            array (
                'id' => 77,
                'name' => 'Christina Pizzino-Catalano',
                'first' => 'Christina',
                'middle' => NULL,
                'last' => 'Pizzino-Catalano',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cpizzino-catalano@niskyschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            69 =>
            array (
                'id' => 78,
                'name' => 'Jennifer Hartnett',
                'first' => 'Jennifer',
                'middle' => NULL,
                'last' => 'Hartnett',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jhartnett@norwood.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$mo2eXgMw2L59EztixtwaI.gFPp/.OqK10j8MnzZn4DsxYs3nkspyq',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            70 =>
            array (
                'id' => 79,
                'name' => 'Rebecca Elpus',
                'first' => 'Rebecca',
                'middle' => NULL,
                'last' => 'Elpus',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'rebecca_elpus@hcpss.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$9gZ1JCbIrOUlg6PoiZcYTeHcXOM8P1RGMol8NoPTHmHVQrvUUy.L2',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            71 =>
            array (
                'id' => 80,
                'name' => 'Charlene Dalrymple',
                'first' => 'Charlene',
                'middle' => NULL,
                'last' => 'Dalrymple',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cdalrymple@easton.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$AFjn1eBDuAPDlNrN4/JTF.L/7SMQaZEpZee/5C5BE4SF9qPjtMuVC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            72 =>
            array (
                'id' => 81,
                'name' => 'Krista Cayea',
                'first' => 'Krista',
                'middle' => NULL,
                'last' => 'Cayea',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kcayea@onteora.k12.ny.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$D/PcqtY2gc0mkEXBkELC6O7tBuD89KMex0BRJRRfMJ98nTQ9a0RUi',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            73 =>
            array (
                'id' => 82,
                'name' => 'Jeff Beyers',
                'first' => 'Jeff',
                'middle' => NULL,
                'last' => 'Beyers',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jbeyers2@bcps.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$eFKVYAynmu4asVIBiGoi0eCXuAxrWqJxyNZWCJMKbaqEF5CV8GMxa',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            74 =>
            array (
                'id' => 83,
                'name' => 'Jon Simmons',
                'first' => 'Jon',
                'middle' => NULL,
                'last' => 'Simmons',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'simmonsj@peabody.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            75 =>
            array (
                'id' => 84,
                'name' => 'Barbara Welsheimer',
                'first' => 'Barbara',
                'middle' => NULL,
                'last' => 'Welsheimer',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'bjwelsheimer@ccps.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            76 =>
            array (
                'id' => 85,
                'name' => 'Terry Bojanowski',
                'first' => 'Terry',
                'middle' => NULL,
                'last' => 'Bojanowski',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'tbojanowski@pointpleasant.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Mgw41WYUucqHO.4wf5KxguSHDZpmBQGEMmXpGqbByF/bfbK5nom9m',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            77 =>
            array (
                'id' => 86,
                'name' => 'Ken Myers',
                'first' => 'Ken',
                'middle' => NULL,
                'last' => 'Myers',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kmyers10@verizon.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            78 =>
            array (
                'id' => 87,
                'name' => 'Matthew Swiss',
                'first' => 'Matthew',
                'middle' => NULL,
                'last' => 'Swiss',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mswiss@rtnj.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            79 =>
            array (
                'id' => 88,
                'name' => 'Barbara Retzko',
                'first' => 'Barbara',
                'middle' => NULL,
                'last' => 'Retzko',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'barbararetzko@hotmail.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            80 =>
            array (
                'id' => 90,
                'name' => 'Mandy Ball',
                'first' => 'Mandy',
                'middle' => NULL,
                'last' => 'Ball',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mball@rockbridge.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8H4DYpmjxfen2Usaaau/SeLbJKWKNEkUwH3ePfDhXqmmF.eMbaKWO',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            81 =>
            array (
                'id' => 91,
                'name' => 'Patrick Hachey',
                'first' => 'Patrick',
                'middle' => NULL,
                'last' => 'Hachey',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'phachey@roxbury.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$n3yi03wBJAxpJNXDI9/POOgArmxmIsW6Ec.MvOjy0e4ntZN.Ruqau',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            82 =>
            array (
                'id' => 92,
                'name' => 'R. Daniel Salyerds',
                'first' => 'R. Daniel',
                'middle' => NULL,
                'last' => 'Salyerds',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'rsalyerds@roxbury.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            83 =>
            array (
                'id' => 93,
                'name' => 'Krista Sweer',
                'first' => 'Krista',
                'middle' => NULL,
                'last' => 'Sweer',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'ksweer@roxbury.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            84 =>
            array (
                'id' => 94,
                'name' => 'Karen DiMartino',
                'first' => 'Karen',
                'middle' => NULL,
                'last' => 'DiMartino',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kdimartino@sayvilleschools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$nraeD.JgGfmq/hmvzP5c9ueZmeTSy04JihfN.kpN72gdoHpfJBIBa',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            85 =>
            array (
                'id' => 95,
                'name' => 'Robert DiLauro',
                'first' => 'Robert',
                'middle' => NULL,
                'last' => 'DiLauro',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'rdilauro@lrhsd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$MCuLAvONbLOag9HgucsEje/Uy9gqRIBUUnkX39F//8iUgdJIU9S96',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            86 =>
            array (
                'id' => 96,
                'name' => 'Gina Kehl',
                'first' => 'Gina',
                'middle' => NULL,
                'last' => 'Kehl',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'gkehl@lrhsd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$3ViTpSvfr2ZWi1ZcAcsuUexlRlJww6TOJP7TufDrbhWNb4MRn2xxe',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            87 =>
            array (
                'id' => 97,
                'name' => 'Samuel Bianco',
                'first' => 'Samuel',
                'middle' => NULL,
                'last' => 'Bianco',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'biancos@sbregional.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ALyw5dSfb2sTYwhlKF9LMO6dGGYEhfalCaQvyheF3/EXx0t3BwmGu',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            88 =>
            array (
                'id' => 98,
                'name' => 'Jereme Martineau',
                'first' => 'Jereme',
                'middle' => NULL,
                'last' => 'Martineau',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jmartineau@swindsor.k12.ct.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            89 =>
            array (
                'id' => 99,
                'name' => 'Laura Ann Lopez',
                'first' => 'Laura Ann',
                'middle' => NULL,
                'last' => 'Lopez',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'Laura.lopez@sparta.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bm7NikqZEH.PG5ocAbphIutdMBZUfVsyTJLdel0zEOIOIrzLBoZUi',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            90 =>
            array (
                'id' => 100,
                'name' => 'Ann Murphy',
                'first' => 'Ann',
                'middle' => NULL,
                'last' => 'Murphy',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'amurphy@spencerportschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            91 =>
            array (
                'id' => 101,
                'name' => 'Erik Clayton',
                'first' => 'Erik',
                'middle' => NULL,
                'last' => 'Clayton',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'elc19@scasd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$R.tIbNQaVE./Nl0MaBy9y.0aRPOJFh6IUoeNjf9kD4u/fxP8zbswO',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            92 =>
            array (
                'id' => 103,
                'name' => 'Christopher Nickelson-Mann',
                'first' => 'Christopher',
                'middle' => NULL,
                'last' => 'Nickelson-Mann',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'luvs2sing87@yahoo.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            93 =>
            array (
                'id' => 104,
                'name' => 'Dan King',
                'first' => 'Dan',
                'middle' => NULL,
                'last' => 'King',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'dking@summit.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OlhGzsezd/EnO3Tnb1xSWuL9QFjAH3qRD7AF5LHtmMFU30jlRzXsC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            94 =>
            array (
                'id' => 105,
                'name' => 'Charles Bateman',
                'first' => 'Charles',
                'middle' => NULL,
                'last' => 'Bateman',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cbateman@susq.k12.pa.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$aq/zkJJCA/knnjAD8weEWeFtMqDiZcHZ3hkMpvn/jxmkCObbyLyeq',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            95 =>
            array (
                'id' => 106,
                'name' => 'Jim Millar',
                'first' => 'Jim',
                'middle' => NULL,
                'last' => 'Millar',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'jmillar@tenafly.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            96 =>
            array (
                'id' => 107,
                'name' => 'William Alford',
                'first' => 'William',
                'middle' => NULL,
                'last' => 'Alford',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'walford@pennington.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$WPArujNtplY.Zd8kw1USdu/1KlDoUauJfGcFUravirQvAyuwLXaKa',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            97 =>
            array (
                'id' => 108,
                'name' => 'Dustin Ramirez',
                'first' => 'Dustin',
                'middle' => NULL,
                'last' => 'Ramirez',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'dustin.ramirez@stonybrookschool.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            98 =>
            array (
                'id' => 109,
                'name' => 'Kevin Boehm',
                'first' => 'Kevin',
                'middle' => NULL,
                'last' => 'Boehm',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kboehm@vtsd.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$dssdu0uUKc845lD7dk14H.vUb1Kq0wWaaQLE9xM4IHtifYAchWJoi',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            99 =>
            array (
                'id' => 110,
                'name' => 'Claire Ma',
                'first' => 'Claire',
                'middle' => NULL,
                'last' => 'Ma',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cma@veronaschools.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$IGZhW19bgJ/yxSOsI92AhOPV14sTIqiT5RY9ttW68SWJJJV.nMbpq',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            100 =>
            array (
                'id' => 111,
                'name' => 'Andrew Finck',
                'first' => 'Andrew',
                'middle' => NULL,
                'last' => 'Finck',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'afinck@nhvweb.net',
                'email_verified_at' => NULL,
                'password' => '$2y$10$0Q5C2HO..5uRYSozSOoHZuWjxeAnh9SEzGHqDNbyuElzL4HCCFcFC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            101 =>
            array (
                'id' => 112,
                'name' => 'Christine Molnar',
                'first' => 'Christine',
                'middle' => NULL,
                'last' => 'Molnar',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'cmolnarmusic@gmail.com',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            102 =>
            array (
                'id' => 113,
                'name' => 'Kelly Butler',
                'first' => 'Kelly',
                'middle' => NULL,
                'last' => 'Butler',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kelly.butler@walterjohnson.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$H0cn1E4HmGVSHQhZf63aOeptJ6s2wcjS/kWQPDyOsdVsMwT4Yoh2C',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            103 =>
            array (
                'id' => 114,
                'name' => 'Alyssa Navarro',
                'first' => 'Alyssa',
                'middle' => NULL,
                'last' => 'Navarro',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'AlyssaNavarro@walthampublicschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            104 =>
            array (
                'id' => 115,
                'name' => 'Linda Contino',
                'first' => 'Linda',
                'middle' => NULL,
                'last' => 'Contino',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'lcontin2@3villagecsd.k12.ny.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FkCXD/81tfg0kJlhreTHF.JLmJloDomva8wjKjGo0aXTWUBx04LK.',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            105 =>
            array (
                'id' => 116,
                'name' => 'Lauren Voight',
                'first' => 'Lauren',
                'middle' => NULL,
                'last' => 'Voight',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'voightl@warrenhills.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            106 =>
            array (
                'id' => 117,
                'name' => 'Debra Kline-Smith',
                'first' => 'Debra',
                'middle' => NULL,
                'last' => 'Kline-Smith',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'dkline-smith@warwicksd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$58ra6GLphSbqM/Zwdw4F9.EiMitenIQX5jEKaPjO81CtcdShkvLqy',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            107 =>
            array (
                'id' => 118,
                'name' => 'Doug C. Heyburn',
                'first' => 'Doug',
                'middle' => 'C.',
                'last' => 'Heyburn',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'doug.heyburn@wmtps.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$ZnRVqxZ.usP7TiqEIyxpgurrgRgleAXyuVO0fVzNSNW..JuxUqIpC',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            108 =>
            array (
                'id' => 119,
                'name' => 'Mark Stingle',
                'first' => 'Mark',
                'middle' => NULL,
                'last' => 'Stingle',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mstingle@wmrhsd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            109 =>
            array (
                'id' => 120,
                'name' => 'Joseph Fritz',
                'first' => 'Joseph',
                'middle' => NULL,
                'last' => 'Fritz',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'joseph.fritz@wwrsd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$HaJwutM5VcJ.OCNu0iXD7.C6Tf58xcIZ28F20QDn9ksOWNwumiN8u',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            110 =>
            array (
                'id' => 121,
                'name' => 'Kent Weaver',
                'first' => 'Kent',
                'middle' => NULL,
                'last' => 'Weaver',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kweaver@wasd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            111 =>
            array (
                'id' => 122,
                'name' => 'Matthew Albright',
                'first' => 'Matthew',
                'middle' => NULL,
                'last' => 'Albright',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'matthew_d_albright@mcpsmd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$hnOE00sHZx1ehwZ7s0bYfOMKC4L9i1obXMhipvFmzbNJAzz8g2qxS',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            112 =>
            array (
                'id' => 123,
                'name' => 'Elizabeth Amory',
                'first' => 'Elizabeth',
                'middle' => NULL,
                'last' => 'Amory',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'elizabeth.amory@woodbridge.k12.nj.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$A4Cm3zU6CH2usv6SWQDjaOcoNy69dYckDEOJooHw0YC4U.QoUXTL6',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            113 =>
            array (
                'id' => 124,
                'name' => 'Brendan B. Moore',
                'first' => 'Brendan B.',
                'middle' => NULL,
                'last' => 'Moore',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'bmoore2@lrhsd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            114 =>
            array (
                'id' => 130,
                'name' => 'Patrick B. Phillips',
                'first' => 'Patrick B.',
                'middle' => NULL,
                'last' => 'Phillips',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'pphillips@twpunionschools.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            115 =>
            array (
                'id' => 131,
                'name' => 'Gordon Kaslusky',
                'first' => 'Gordon',
                'middle' => NULL,
                'last' => 'Kaslusky',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'gkaslusky@mbgsd.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$082zX5Dc954b9YzZRGW1TO5iHy4ipTxWPfkRubUXfeao8O/lBp8AW',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            116 =>
            array (
                'id' => 132,
                'name' => 'Julie Katz',
                'first' => 'Julie',
                'middle' => NULL,
                'last' => 'Katz',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'julie.katz@redclay.k12.de.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$vDSYvgCqsPI/oHK5chWo4eUxq4tP/xOrzD9LGhdDnbbvHc36WkB5.',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            117 =>
            array (
                'id' => 133,
                'name' => 'David Stephenson',
                'first' => 'David',
                'middle' => NULL,
                'last' => 'Stephenson',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'dstephenson@lexington1.net',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            118 =>
            array (
                'id' => 134,
                'name' => 'Daniel Malloy',
                'first' => 'Daniel',
                'middle' => NULL,
                'last' => 'Malloy',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'malloyd@madisonnjps.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$VLIGNnVwObfgzmdltjwnDOitIsR60WUnux6BE.vZneomD98QjpCiK',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            119 =>
            array (
                'id' => 135,
                'name' => 'Amanda Hanzlik',
                'first' => 'Amanda',
                'middle' => NULL,
                'last' => 'Hanzlik',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'ahanzlik@eosmith.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$22n9drO4x96BfoZsyU70aeHQfyjKM5LUI4YXc8rEFnjl3LFZ26odG',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            120 =>
            array (
                'id' => 136,
                'name' => 'Murray Kidd',
                'first' => 'Murray',
                'middle' => NULL,
                'last' => 'Kidd',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'mkidd@easton.k12.ma.us',
                'email_verified_at' => NULL,
                'password' => '$2y$10$WW16nCC4v0Ln5VZdI4fIJOf.yMUV87k/HH6oqnCFTPBEmZln5YgPG',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            121 =>
            array (
                'id' => 139,
                'name' => 'Adam Good',
                'first' => 'Adam',
                'middle' => NULL,
                'last' => 'Good',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'adam.good@ebnet.org',
                'email_verified_at' => NULL,
                'password' => '$2y$10$e44jORqdrYOct.GsxZRzZ.ii1RdSAkemL1qvrA1V5HdWgZWrcws7W',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
            122 =>
            array (
                'id' => 142,
                'name' => 'Kristen Markowski',
                'first' => 'Kristen',
                'middle' => NULL,
                'last' => 'Markowski',
                'honorific_id' => NULL,
                'suffix' => NULL,
                'email' => 'kmarkowski@mhrd.org',
                'email_verified_at' => NULL,
                'password' => 'password',
                'remember_token' => NULL,
                'created_at' => '2022-06-09 07:41:41',
                'updated_at' => '2022-06-09 07:41:41',
            ),
        ));

        //add Domain Owner role
        $do = User::find(1);
        $do->roles()->attach(Role::OWNER);
    }
}
