<?php

namespace Tests\Feature\Admin\Rosters;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AcceptedsPageTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_open_page()
    {
        $this->withoutExceptionHandling();

        $response = $this->actingAs($this->user)
            ->get('rosters/accepteds')
            ->assertStatus(200);
    }
}
